# Generated by Django 5.0.6 on 2024-06-23 02:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='avatares')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
            options={
                'verbose_name': 'Clientes',
                'verbose_name_plural': 'Clientes',
                'ordering': ('nombre', 'apellido', 'email'),
                'unique_together': {('nombre', 'apellido', 'email')},
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('categoria', models.CharField(max_length=40)),
                ('precio', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Productos',
                'verbose_name_plural': 'Productos',
                'ordering': ('nombre', 'precio', 'cantidad'),
                'unique_together': {('nombre', 'precio', 'cantidad')},
            },
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('cuil', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Proveedores',
                'verbose_name_plural': 'Proveedores',
                'ordering': ('razon_social', 'email', 'cuil'),
                'unique_together': {('razon_social', 'email', 'cuil')},
            },
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_orden', models.IntegerField()),
                ('fecha_venta', models.DateField()),
                ('entregado', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Ventas',
                'verbose_name_plural': 'Ventas',
                'ordering': ('num_orden', 'fecha_venta', 'entregado'),
                'unique_together': {('num_orden', 'fecha_venta', 'entregado')},
            },
        ),
    ]
